### ISSUE TITLE
Add a command to see a list of IRC users

### ISSUE THREAD

**Issue by tox-user** [envsh/matterbridge#12]
There should be a channel command /users or !users or something similar that would allow to see a list of people connected to the synced IRC channel. toxync would respond with a message containing the list. Messages containing that command would not be sent to IRC and the output of that command from toxync would not be synced either.

**Comment by envsh** [comment]
if the result send to tox group, the message should be long.

irc's /names is show only on client, not noise for others.

**Comment by envsh** [comment]
there is a `!users` command now
note for long message here.

**Comment by tox-user** [comment]
It works on Tox and is really good! Only the `!users` message that is sent by user should not be synced to IRC. Is there a similar command for people on IRC to see Tox users?

**Comment by tox-user** [comment]
It would be great if the command also said how many users there are - showed the count.

**Comment by envsh** [comment]
ok then, all done.

send `!help` for help
