### ISSUE TITLE
Russian Tox Chat should be connected to KalinaBot

### ISSUE THREAD

**Issue by tox-user** [envsh/matterbridge#17]
Russian Tox Chat in toxync is connected to Groupbot's Russian Tox Chat which is out of sync with the original channel from KalinaBot.
KalinaBot's ID:
12EDB939AA529641CE53830B518D6EB30241868EE0E5023C46A372363CAEC91C2C948AEFE4EB

**Comment by envsh** [comment]
it's offline in my friend list long time, thought it lost.

**Comment by envsh** [comment]
fixed
